#需要指定的配置项
#1. 全局配置的开发人员名称(author)
#2. 数据库配置 
#3. 跟包相关的配置项的模块名(moduleName)与父包名(parent)
#4. 策略配置项的需要生成的表(include,数组格式)
#5. 自定义配置,配置自定义功能


#全局配置
GlobalConfig: 
  fileOverride: false #是否覆盖已有文件
  author: lhb #开发人员
  
#数据库配置 
DataSourceConfig: 
  DbType: com.baomidou.mybatisplus.annotation.DbType.SQL_SERVER #数据库类型
  url: jdbc:sqlserver://192.168.10.201:1433;DatabaseName=device
  driverName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  username: report
  password: 1q2w3e4r#

#跟包相关的配置项
PackageConfig: 
  parent: com.combest #父包名。如果为空，将下面子包名必须写全部， 否则就只需写子包名
  entity: bean #Entity包名
  moduleName: device #模块名
  
#模板路径配置项
TemplateConfig: 
  xml: #空就行

#策略配置项
StrategyConfig: 
  naming: com.baomidou.mybatisplus.generator.config.rules.NamingStrategy.underline_to_camel #表名映射到实体策略，带下划线的转成驼峰
  columnNaming: com.baomidou.mybatisplus.generator.config.rules.NamingStrategy.underline_to_camel #列名映射到类型属性策略，带下划线的转成驼峰
  entityLombokModel: true #实体类使用lombok
  include: #需要包含的表名，允许正则表达式（与exclude二选一配置）
    supplier
  entityBooleanColumnRemoveIsPrefix: true #Boolean类型字段是否移除is前缀  比如 : 数据库字段名称 : 'is_xxx',类型为 : tinyint. 在映射实体的时候则会去掉is,在实体类中映射最终结果为 xxx

#自定义配置项
InjectionConfig: 
  #假删除
  fdFlag: false #是否启用假删除模式
  fdFieldName: is_delete #如启用假删除,需指定标记删除的属性名
  fdFieldType: int #假删除的属性类型  int 或 varchar  仅支持此两种
  fdValue: 1 #确认删除的值
  
  DeleteMethodFlag: true #是否需要删除方法,如果启用假删除,可以设为false不需要删除方法
  
  







  